const tableData = [
    {
      name: "John Doe",
      status: "Working",
      role: "Product Manager",
      email: "john@example.com",
      teams: ["Developer", "Backend", "Frontend", "Sales", "HR"],
      image: "https://randomuser.me/api/portraits/men/1.jpg",
    },
    {
      name: "Jane Smith",
      status: "On Leave",
      role: "Software Engineer",
      email: "jane@example.com",
      teams: ["QA", "Testing"],
      image: "https://randomuser.me/api/portraits/women/2.jpg",
    },
    {
      name: "Alice Johnson",
      status: "Working",
      role: "Designer",
      email: "alice@example.com",
      teams: ["Design", "UX Research", "Product", "Branding", "Marketing"],
      image: "https://randomuser.me/api/portraits/women/5.jpg",
    },
    {
      name: "Michael Brown",
      status: "Working",
      role: "Backend Developer",
      email: "michael@example.com",
      teams: ["Engineering", "DevOps", "Security", "Cloud"],
      image: "https://randomuser.me/api/portraits/men/3.jpg",
    },
    {
      name: "David Wilson",
      status: "Working",
      role: "Frontend Developer",
      email: "david@example.com",
      teams: ["UI", "React", "Angular"],
      image: "https://randomuser.me/api/portraits/men/4.jpg",
    },
    {
      name: "Sarah Davis",
      status: "On Leave",
      role: "HR Manager",
      email: "sarah@example.com",
      teams: ["Recruitment", "Employee Relations"],
      image: "https://randomuser.me/api/portraits/women/6.jpg",
    },
    {
      name: "Robert White",
      status: "Working",
      role: "DevOps Engineer",
      email: "robert@example.com",
      teams: ["Infrastructure", "CI/CD", "Cloud"],
      image: "https://randomuser.me/api/portraits/men/7.jpg",
    },
    {
      name: "Emma Thomas",
      status: "Working",
      role: "Data Scientist",
      email: "emma@example.com",
      teams: ["AI", "ML", "Big Data"],
      image: "https://randomuser.me/api/portraits/women/8.jpg",
    },
    {
      name: "Liam Garcia",
      status: "Working",
      role: "Software Architect",
      email: "liam@example.com",
      teams: ["System Design", "Scalability"],
      image: "https://randomuser.me/api/portraits/men/9.jpg",
    },
    {
      name: "Olivia Martinez",
      status: "On Leave",
      role: "Project Manager",
      email: "olivia@example.com",
      teams: ["Agile", "Scrum"],
      image: "https://randomuser.me/api/portraits/women/10.jpg",
    },
    {
      name: "Noah Anderson",
      status: "Working",
      role: "Security Analyst",
      email: "noah@example.com",
      teams: ["Cybersecurity", "Network Security"],
      image: "https://randomuser.me/api/portraits/men/11.jpg",
    },
    {
      name: "Sophia Taylor",
      status: "Working",
      role: "Business Analyst",
      email: "sophia@example.com",
      teams: ["Strategy", "Market Research"],
      image: "https://randomuser.me/api/portraits/women/12.jpg",
    },
    {
      name: "James Harris",
      status: "On Leave",
      role: "Mobile Developer",
      email: "james@example.com",
      teams: ["iOS", "Android"],
      image: "https://randomuser.me/api/portraits/men/13.jpg",
    },
    {
      name: "Isabella Clark",
      status: "Working",
      role: "Full Stack Developer",
      email: "isabella@example.com",
      teams: ["MERN", "LAMP"],
      image: "https://randomuser.me/api/portraits/women/14.jpg",
    },
    {
      name: "Ethan Lewis",
      status: "Working",
      role: "Cloud Engineer",
      email: "ethan@example.com",
      teams: ["AWS", "Azure", "Google Cloud"],
      image: "https://randomuser.me/api/portraits/men/15.jpg",
    },
    {
      name: "Mia Walker",
      status: "On Leave",
      role: "QA Engineer",
      email: "mia@example.com",
      teams: ["Automation", "Manual Testing"],
      image: "https://randomuser.me/api/portraits/women/16.jpg",
    },
    {
      name: "Benjamin Hall",
      status: "Working",
      role: "Game Developer",
      email: "benjamin@example.com",
      teams: ["Unity", "Unreal Engine"],
      image: "https://randomuser.me/api/portraits/men/17.jpg",
    },
    {
      name: "Charlotte Allen",
      status: "Working",
      role: "Marketing Specialist",
      email: "charlotte@example.com",
      teams: ["SEO", "Content Marketing"],
      image: "https://randomuser.me/api/portraits/women/18.jpg",
    },
    {
      name: "Daniel Young",
      status: "On Leave",
      role: "Database Administrator",
      email: "daniel@example.com",
      teams: ["SQL", "NoSQL", "Data Management"],
      image: "https://randomuser.me/api/portraits/men/19.jpg",
    },
    {
      name: "Amelia King",
      status: "Working",
      role: "Customer Support Lead",
      email: "amelia@example.com",
      teams: ["Support", "User Experience"],
      image: "https://randomuser.me/api/portraits/women/20.jpg",
    },
  ];
  
  export default tableData;
  